# Generated by Django 4.1.1 on 2022-09-27 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('musica', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('album', models.CharField(max_length=50)),
                ('anoPublicacao', models.IntegerField()),
            ],
        ),
    ]
